name: GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate stats image
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          filename: metrics.svg
          theme: dracula
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_limit: 6
          plugin_languages_threshold: 0%
